### ISSUE TITLE
Multiple language support

### ISSUE THREAD

**Issue by fallmats** [loadcoder/loadcoder#48]
Investigate how it would be possible to open up for multiple programming language support. For inspiration look at Selenium/WebDriver. It might be tricky since these tests are aimed to be written and run close to the code. Alternative approach would be to make other language implementations. It would make sense to make a C# implementation since Microsoft VS Load Test is planned to be deprecated.

**Comment by StefanVahlgren** [comment]
@fallmats This won't be dont unfortunately. The effort is too great compared to the gain, and to the fact that there are already other tools for the .NET and JavaScript platform. For C# please look at NBomber. 

Since code oriented tools in its nature are tied to the language they are written in, it would take a complete reimplementation to support another langauge. This is one of the points that you are making in your comment.

Thanks though for great input. Closing this issue
